workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: defalut
      vars:
        FIREBASE_PROJECT: "flutterlab6"
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter packages pub get
     
      - name: Build APK with flutter
        script: |
          flutter build apk --debug
      - name: Create debug and test APK
        script: |
          set -ex
          cd android


